version: '2'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - "./web/src:/web/src"
    ports:
      - "8080:8080"
    environment:
      - SOME_ENV=SOME_VALUE

  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
